name: My GitHub Action
on:
  schedule:
    - cron:  '30 11 * * 1-5'
  push:
    branches: [ EDR ]
  pull_request:
    branches: [ EDR ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # adjust this if needed

    - name: Install dependencies
      run: pip install pandas tenacity requests pydantic openpyxl sseclient retry schedule

    - name: Run the script
      run: python EDRAutomationTesting.py
